language: objective-c
osx_image: xcode7.1
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - pod install
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild test -workspace sf-ios.xcworkspace -scheme sf-ios -sdk iphonesimulator9.1 ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
